# Sentiment Analysis

In [ ]:
import tensorflow_datasets as tfds

imdb, info = tfds.load('imdb_reviews', with_info=True, as_supervised=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete44UQNZ/imdb_reviews-train.tfrecord…

Generating test examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete44UQNZ/imdb_reviews-test.tfrecord*…

Generating unsupervised examples...:   0%|          | 0/50000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete44UQNZ/imdb_reviews-unsupervised.t…

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [ ]:
import numpy as np
train_data, test_data = imdb["train"], imdb["test"]

train_sentences = []
test_sentences = []

train_labels = []
test_labels = []

for sentence, label in train_data:
  train_sentences.append(str(sentence.numpy()))
  train_labels.append(label.numpy())

for sentence, label in test_data:
  test_sentences.append(str(sentence.numpy()))
  test_labels.append(label.numpy())

In [ ]:
train_sentences[0], train_labels[0]

('b"This was an absolutely terrible movie. Don\'t be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie\'s ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor\'s like Christopher Walken\'s good name. I could barely sit through it."',
 0)

In [ ]:
sample = train_sentences[0]
sample = sample.split()
print(len(sample))
sample[:10]

116


['b"This',
 'was',
 'an',
 'absolutely',
 'terrible',
 'movie.',
 "Don't",
 'be',
 'lured',
 'in']

In [ ]:
train_labels = np.array(train_labels)
test_labels = np.array(test_labels)

train_labels.shape, test_labels.shape

((25000,), (25000,))

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

vocab_size = 10000
embedding_dim = 64
max_length = 140

tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(train_sentences)
word_index = tokenizer.word_index
word_index

{'<OOV>': 1,
 'the': 2,
 'and': 3,
 'a': 4,
 'of': 5,
 'to': 6,
 'is': 7,
 'br': 8,
 'in': 9,
 'it': 10,
 'i': 11,
 'this': 12,
 'that': 13,
 'was': 14,
 'as': 15,
 'for': 16,
 'with': 17,
 'movie': 18,
 'but': 19,
 'film': 20,
 "'s": 21,
 'on': 22,
 'you': 23,
 'not': 24,
 'are': 25,
 'his': 26,
 'he': 27,
 'have': 28,
 'be': 29,
 'one': 30,
 'all': 31,
 'at': 32,
 'by': 33,
 'they': 34,
 'an': 35,
 'who': 36,
 'so': 37,
 'from': 38,
 'like': 39,
 'her': 40,
 "'t": 41,
 'or': 42,
 'just': 43,
 'there': 44,
 'about': 45,
 'out': 46,
 "'": 47,
 'has': 48,
 'if': 49,
 'some': 50,
 'what': 51,
 'good': 52,
 'more': 53,
 'very': 54,
 'when': 55,
 'she': 56,
 'up': 57,
 'can': 58,
 'b': 59,
 'time': 60,
 'no': 61,
 'even': 62,
 'my': 63,
 'would': 64,
 'which': 65,
 'story': 66,
 'only': 67,
 'really': 68,
 'see': 69,
 'their': 70,
 'had': 71,
 'were': 72,
 'me': 73,
 'well': 74,
 'we': 75,
 'than': 76,
 'much': 77,
 'been': 78,
 'get': 79,
 'bad': 80,
 'will': 81,
 'people': 82,
 'do': 83,

In [ ]:
train_sequences = tokenizer.texts_to_sequences(train_sentences)
padded_train_sequences = pad_sequences(train_sequences, maxlen=max_length, truncating="post", padding="post")
print(padded_train_sequences.shape)
padded_train_sequences

(25000, 140)


array([[  59,   12,   14, ...,    0,    0,    0],
       [ 256,   28,   78, ...,    0,    0,    0],
       [   1, 6175,    2, ...,    0,    0,    0],
       ...,
       [7629,   37,   11, ..., 2743,   21, 1563],
       [2677,   11,  216, ..., 1048,   37,   31],
       [3875,    5,   31, ...,    1, 2238,   42]], dtype=int32)

In [ ]:
test_sequences = tokenizer.texts_to_sequences(test_sentences)
padded_test_sequences = pad_sequences(test_sequences, maxlen=max_length, truncating="post", padding="post")
print(padded_test_sequences.shape)
padded_test_sequences

(25000, 140)


array([[  59,   44,   25, ...,  158,    3,    2],
       [  59,    4,    1, ...,    6,    1,   16],
       [   1,   18,  301, ..., 2806,   10,   19],
       ...,
       [  59,   92,    1, ...,    6,  359,    3],
       [  59,  103,  627, ...,    0,    0,    0],
       [  59,   34,   43, ...,    0,    0,    0]], dtype=int32)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Bidirectional, Dropout, Dense, Flatten

model = Sequential([
    Embedding(vocab_size, embedding_dim, input_length=max_length),
    Flatten(),
    Dense(10, activation="relu"),
    Dense(1, activation="sigmoid"),
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 140, 64)           640000    
                                                                 
 flatten_1 (Flatten)         (None, 8960)              0         
                                                                 
 dense_2 (Dense)             (None, 10)                89610     
                                                                 
 dense_3 (Dense)             (None, 1)                 11        
                                                                 
Total params: 729,621
Trainable params: 729,621
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(padded_train_sequences, train_labels, epochs=2, validation_data=(padded_test_sequences, test_labels))

Epoch 1/2
782/782 [==============================] - 15s 18ms/step - loss: 0.4461 - accuracy: 0.7812 - val_loss: 0.3708 - val_accuracy: 0.8356
Epoch 2/2
782/782 [==============================] - 16s 20ms/step - loss: 0.1323 - accuracy: 0.9567 - val_loss: 0.4710 - val_accuracy: 0.8138


In [ ]:
infer_text = ["I hate this movie very much, never watch it again"]

text_seq = tokenizer.texts_to_sequences(infer_text)
padded_text_seq = pad_sequences(text_seq, maxlen=max_length, truncating="post", padding="post")
padded_text_seq

array([[ 11, 797,  12,  18,  54,  77, 117, 107,  10, 172,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0]], dtype=int32)

In [ ]:
threshold = 0.5
labels = ['negative', 'positive']
prediction = model.predict(padded_text_seq)
prediction = 0 if prediction < threshold else 1
print(labels[prediction])

1/1 [==============================] - 0s 29ms/step
negative


In [ ]:
embedding_layer = model.layers[0]
weights = embedding_layer.get_weights()[0]
weights

array([[-0.00082552,  0.00735218, -0.00615107, ..., -0.00773776,
         0.01644254, -0.01731146],
       [ 0.03679529,  0.00963966, -0.03848245, ...,  0.0154727 ,
         0.02017927, -0.02298276],
       [-0.02664241, -0.0122497 ,  0.00409113, ..., -0.02969607,
        -0.0103428 , -0.05457977],
       ...,
       [-0.04080749, -0.0506328 , -0.02849244, ..., -0.08205727,
         0.11673706,  0.07886923],
       [-0.08188099,  0.00728733,  0.00771333, ..., -0.00852992,
        -0.00073415, -0.04994433],
       [ 0.02848926,  0.03834461,  0.01061661, ...,  0.05550463,
         0.03156418, -0.02711313]], dtype=float32)

In [ ]:
import io
out_v = io.open('vecs.tsv', 'w', encoding='utf-8')
out_m = io.open('meta.tsv', 'w', encoding='utf-8')

for idx in range(1, vocab_size):
  word = tokenizer.index_word[idx]
  vector = weights[idx]
  out_m.write(word + "\n")
  out_v.write("\t".join([str(x) for x in vector]) + "\n")

out_m.close()
out_v.close()